on: [push]

name: build

jobs:
  runalldays:
    name: Run all solutions
    runs-on: ubuntu-latest

    steps:
    - name: "Clone repository"
      uses: actions/checkout@v4

    - name: "Setup Haskell"
      uses: haskell-actions/setup@v2

    - name: "Run Day 1"
      run: |
        cd day-1
        time runhaskell Part1.hs
        time runhaskell Part2.hs

    - name: "Run Day 2"
      run: |
        cd day-2
        time runhaskell Part1.hs
        time runhaskell Part2.hs

    - name: "Run Day 3"
      run: |
        cd day-3
        cabal install --lib regex-tdfa
        time runhaskell Part1.hs
        time runhaskell Part2.hs
