on: [push]

name: build

jobs:
  runalldays:
    name: Run all solutions
    runs-on: ubuntu-latest

    steps:
    - name: "Clone repository"
      uses: actions/checkout@v4

    - name: "Setup Haskell"
      uses: haskell-actions/setup@v2

    - name: "Build all executables"
      run: cabal build

    - name: "Run Day 1"
      run: |
        cabal run Day1Part1
        cabal run Day1Part2

    - name: "Run Day 2"
      run: |
        cabal run Day2Part1
        cabal run Day2Part2

    - name: "Run Day 3"
      run: |
        cabal run Day3Part1
        cabal run Day3Part2

    - name: "Run Day 4"
      run: |
        cabal run Day4Part1
        cabal run Day4Part2

    - name: "Run Day 5"
      run: |
        cabal run Day5Part1
        cabal run Day5Part2

    - name: "Run Day 6"
      run: |
        cabal run Day6Part1
