on: [push]

name: build

jobs:
  runalldays:
    name: Run all solutions
    runs-on: ubuntu-latest

    steps:
    - name: "Clone repository"
      uses: actions/checkout@v4

    - name: "Setup Haskell"
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.12.1.0'

    - name: "Build all executables"
      run: cabal build

    - name: "Run Day 1"
      run: |
        (( $(cabal run Day1Part1) == 765748   ))
        echo "Part 1: OK"
        (( $(cabal run Day1Part2) == 27732508 ))
        echo "Part 2: OK"

    - name: "Run Day 2"
      run: |
        (( $(cabal run Day2Part1) == 660 ))
        echo "Part 1: OK"
        (( $(cabal run Day2Part2) == 689 ))
        echo "Part 2: OK"

    - name: "Run Day 3"
      run: |
        (( $(cabal run Day3Part1) == 170807108 ))
        echo "Part 1: OK"
        (( $(cabal run Day3Part2) == 74838033  ))
        echo "Part 2: OK"

    - name: "Run Day 4"
      run: |
        (( $(cabal run Day4Part1) == 2547 ))
        echo "Part 1: OK"
        (( $(cabal run Day4Part2) == 1939 ))
        echo "Part 2: OK"

    - name: "Run Day 5"
      run: |
        (( $(cabal run Day5Part1) == 5732 ))
        echo "Part 1: OK"
        (( $(cabal run Day5Part2) == 4716 ))
        echo "Part 2: OK"

    - name: "Run Day 6"
      run: |
        (( $(cabal run Day6Part1) == 5153 ))
        echo "Part 1: OK"
        (( $(cabal run Day6Part2 -- +RTS -N4 -RTS) == 1711 ))
        echo "Part 2: OK"

    - name: "Run Day 7"
      run: |
        (( $(cabal run Day7Part1) == 7885693428401 ))
        echo "Part 1: OK"
        (( $(cabal run Day7Part2) == 348360680516005 ))
        echo "Part 2: OK"

    - name: "Run Day 8"
      run: |
        (( $(cabal run Day8Part1) == 269 ))
        echo "Part 1: OK"
        (( $(cabal run Day8Part2) == 949 ))
        echo "Part 2: OK"

    - name: "Run Day 9"
      run: |
        (( $(cabal run Day9Part1) == 6299243228569 ))
        echo "Part 1: OK"

    - name: "Run Day 11"
      run: |
        (( $(cabal run Day11Part1) == 183248 ))
        echo "Part 1: OK"
        (( $(python3 day-11/Part2.py) == 218811774248729 ))
        echo "Part 2: OK"

    - name: "Run Day 12"
      run: |
        (( $(python3 day-12/Part1.py) == 1473276 ))
        echo "Part 1: OK"
