on: [push]

name: build

jobs:
  runalldays:
    name: Run all solutions
    runs-on: ubuntu-latest

    steps:
    - name: "Clone repository"
      uses: actions/checkout@v4

    - name: "Run Day 1"
      uses: haskell-actions/setup@v2
      run: |
        cd day-1
        runhaskell Part1.hs
